"""
Static site builder for synthetic content demo.
Wraps generated articles in HTML with mandatory disclaimers and no-index tags.
Outputs to /docs (GitHub Pages compatible) or /dist (Netlify compatible).
"""

from __future__ import annotations
import json
import os
import shutil
from pathlib import Path
from datetime import datetime, timezone
from typing import Optional


DISCLAIMER_BANNER = """
<div class="disclaimer">
  <strong>⚠ SYNTHETIC TEST CONTENT — NOT REAL</strong><br>
  This article was generated by an AI system for internal stress testing of
  sentiment analysis algorithms. All companies, tickers, events, and figures
  are entirely fictional. This content has no relation to any real securities,
  persons, or events. Do not make financial decisions based on this content.
</div>
""".strip()

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Prevent ALL search engine indexing -->
  <meta name="robots" content="noindex, nofollow, noarchive, nosnippet">
  <meta name="googlebot" content="noindex, nofollow">
  <title>[SYNTHETIC] {ticker} — {scenario_id}</title>
  <style>
    body {{
      font-family: Georgia, serif;
      max-width: 720px;
      margin: 0 auto;
      padding: 2rem 1rem;
      color: #111;
      background: #fafafa;
    }}
    .disclaimer {{
      background: #fff3cd;
      border: 2px solid #f0a500;
      border-radius: 6px;
      padding: 1rem 1.25rem;
      margin-bottom: 2rem;
      font-family: sans-serif;
      font-size: 0.9rem;
      line-height: 1.5;
    }}
    .meta {{
      font-family: sans-serif;
      font-size: 0.8rem;
      color: #666;
      margin-bottom: 1.5rem;
      border-bottom: 1px solid #ddd;
      padding-bottom: 0.75rem;
    }}
    .sentiment-badge {{
      display: inline-block;
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 0.75rem;
      font-weight: bold;
      text-transform: uppercase;
    }}
    .bullish {{ background: #d4edda; color: #155724; }}
    .bearish {{ background: #f8d7da; color: #721c24; }}
    .neutral  {{ background: #e2e3e5; color: #383d41; }}
    .article-body {{ line-height: 1.8; white-space: pre-wrap; }}
    nav {{ font-family: sans-serif; font-size: 0.85rem; margin-bottom: 1.5rem; }}
    nav a {{ color: #0066cc; text-decoration: none; }}
  </style>
</head>
<body>
  {disclaimer}

  <nav><a href="index.html">← Back to index</a></nav>

  <div class="meta">
    <span class="sentiment-badge {polarity}">{polarity}</span>
    &nbsp;
    Ticker: <strong>${ticker}</strong> &nbsp;|&nbsp;
    Scenario: {scenario_id} &nbsp;|&nbsp;
    Intensity: {intensity} &nbsp;|&nbsp;
    Sentiment score: {sentiment_score} &nbsp;|&nbsp;
    Format: {content_format} &nbsp;|&nbsp;
    Generated: {timestamp}
  </div>

  <div class="article-body">{article_text}</div>

  <hr style="margin-top:3rem">
  <p style="font-family:sans-serif;font-size:0.75rem;color:#999">
    [SYNTHETIC_TEST_CONTENT — NOT REAL — FOR INTERNAL STRESS TESTING ONLY]<br>
    Generated by synthetic-sentiment-engine for algorithmic trading research.
  </p>
</body>
</html>
"""

INDEX_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="robots" content="noindex, nofollow, noarchive, nosnippet">
  <meta name="googlebot" content="noindex, nofollow">
  <title>Synthetic Sentiment Engine — Test Dataset</title>
  <style>
    body {{ font-family: sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem 1rem; }}
    .disclaimer {{
      background: #fff3cd; border: 2px solid #f0a500;
      border-radius: 6px; padding: 1rem 1.25rem; margin-bottom: 2rem; font-size: 0.9rem;
    }}
    table {{ width: 100%; border-collapse: collapse; font-size: 0.85rem; }}
    th, td {{ text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #ddd; }}
    th {{ background: #f0f0f0; }}
    .bullish {{ color: #155724; font-weight: bold; }}
    .bearish {{ color: #721c24; font-weight: bold; }}
    a {{ color: #0066cc; }}
  </style>
</head>
<body>
  {disclaimer}

  <h1>Synthetic Sentiment Test Dataset</h1>
  <p>Generated: {generated_at} &nbsp;|&nbsp; Total articles: {total}</p>

  <table>
    <thead>
      <tr>
        <th>Ticker</th>
        <th>Polarity</th>
        <th>Intensity</th>
        <th>Score</th>
        <th>Format</th>
        <th>Scenario</th>
        <th>Link</th>
      </tr>
    </thead>
    <tbody>
      {rows}
    </tbody>
  </table>
</body>
</html>
"""

ROBOTS_TXT = """\
# Disallow all crawlers — this site contains synthetic test content only
User-agent: *
Disallow: /
"""


def build_static_site(
    results_json_path: str,
    output_dir: str = "docs",       # "docs" = GitHub Pages, "dist" = Netlify
) -> None:
    out = Path(output_dir)
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    with open(results_json_path) as f:
        results = json.load(f)

    # Flatten — results_json may be summary or raw content list
    articles = results if isinstance(results, list) else results.get("contents", [])

    index_rows = []
    generated_count = 0

    for i, item in enumerate(articles):
        ticker = item.get("ticker", "UNK")
        polarity = item.get("polarity", "neutral")
        intensity = item.get("intensity", 0.0)
        score = item.get("sentiment_score") or 0.0
        fmt = item.get("format", "unknown")
        scenario = item.get("metadata", {}).get("scenario_id", item.get("scenario_id", "unknown"))
        text = item.get("text", "[no content]")
        timestamp = item.get("timestamp", "")

        filename = f"article_{i:04d}_{ticker}_{polarity}.html"
        filepath = out / filename

        page_html = HTML_TEMPLATE.format(
            disclaimer=DISCLAIMER_BANNER,
            ticker=ticker,
            scenario_id=scenario,
            polarity=polarity,
            intensity=f"{intensity:.2f}",
            sentiment_score=f"{score:+.2f}",
            content_format=fmt,
            timestamp=timestamp[:19] if timestamp else "N/A",
            article_text=text,
        )
        filepath.write_text(page_html, encoding="utf-8")
        generated_count += 1

        index_rows.append(
            f'<tr>'
            f'<td>${ticker}</td>'
            f'<td class="{polarity}">{polarity}</td>'
            f'<td>{intensity:.2f}</td>'
            f'<td>{score:+.2f}</td>'
            f'<td>{fmt}</td>'
            f'<td>{scenario}</td>'
            f'<td><a href="{filename}">view</a></td>'
            f'</tr>'
        )

    # Write index
    index_html = INDEX_TEMPLATE.format(
        disclaimer=DISCLAIMER_BANNER,
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        total=generated_count,
        rows="\n      ".join(index_rows),
    )
    (out / "index.html").write_text(index_html, encoding="utf-8")

    # Write robots.txt — block all crawlers
    (out / "robots.txt").write_text(ROBOTS_TXT, encoding="utf-8")

    # Write _headers for Netlify (also sets X-Robots-Tag at HTTP level)
    netlify_headers = """\
/*
  X-Robots-Tag: noindex, nofollow
  Cache-Control: no-store
"""
    (out / "_headers").write_text(netlify_headers, encoding="utf-8")

    print(f"Site built: {generated_count} pages → {out}/")
    print(f"  index.html       — article index")
    print(f"  robots.txt       — blocks all crawlers")
    print(f"  _headers         — Netlify HTTP-level noindex")
    print(f"\nDeploy options:")
    print(f"  GitHub Pages: push repo, set Pages source to /{output_dir}")
    print(f"  Netlify:      drag-and-drop the '{output_dir}' folder at app.netlify.com/drop")


if __name__ == "__main__":
    import sys
    results_path = sys.argv[1] if len(sys.argv) > 1 else "stress_test_results.json"
    output = sys.argv[2] if len(sys.argv) > 2 else "docs"
    build_static_site(results_path, output)
